### PR TITLE
Linux 32/64 Makefiles : Update linker parameters for GCC 4.5+

### PR DESCRIPTION
**Pull request by tcoppex**
Hi,

This updates the Linux 32/64 Makefiles to handle the new linking behavior starting from GCC 4.5, where symbols are not resolved anymore in indirectly linked shared libraries (_-Wl,--as-needed_ set as a default linker flags). It pass the compilation against GCC 4.4.7, too.

It simply changed the group settings for _-Wl,--no-as-needed_ and put **NvGLUtils*** and **glfw3** as last dependencies. This was edited via a raw, bulk, replace function. So I just left the misfit lines commented out.

Thanks  :+1:

### CODE REVIEW

**Comment by larsbishop** [comment]
Sorry for the delay.  We were in the throes of the 2.11 release (posted yesterday).  We actually generate the Makefiles internally using a version of the tool XPJ (http://sourceforge.net/projects/xpj/) with some extensions.  I'll make the changes to our makefile generation code internally, and plan to update this with the 2.12 release, hopefully in a month or so.

Thanks!

**Comment by tcoppex** [comment]
Nice. I was wondering how you managed so many Makefiles, it makes sense now.
Sounds greats to me anyways, thanks.

**Comment by ddurnev** [comment]
There is an issue with the supplied static version of glfw3 library on Ubuntu linux 15.04 64 bit - its first call `glfwCreateWindow()`
crashes. You should not link against it(why do this?), but rather use dynamic lib dependency supplied by the distro. At least for me relinking to .so from ubuntu fixed the crash nicely. So I suggest to remove your supplied version(in case of linux) and link against standard glfw(not glfw3) adding it to dependencies.

**Comment by larsbishop** [comment]
Thanks for the bug note – I’ll work with the folks that support the desktop Linux version and see if we can repro the issue and your successful fix!


Lmb

**Comment by ddurnev** [comment]
BTW you don't have "issues" link here, so I had to add my comment to existing pull request instead of creating an issue. And why you supplied the (standard) glfw (and GLEW) libraries as binary archives - I think all major distros can get 'em installed via package managers? Is it somehow related to Makefile generation process by XPJ?

**Comment by larsbishop** [comment]
The reason we include the source and the precompiled binaries for GLFW3 is that we want to 1) ensure that the package we provide is self-consistent and avoid any differences with what might be on the system and 2) to allow us to make extensions or modifications moving forward.  While this seems to be causing the reverse for you in terms of 1), I can't seem to reproduce it yet.  I just created a base Ubuntu 15.04 bootable USB, and did not have the crash you note - even after installing the glfw3 packages via the package manager.

I'll continue looking into this, but right now, I am not expecting to make a change to how we link GLFW.  The most likely move w.r.t. GFLW in the future for these samples will be to move away from GLFW to our own (likely lighter weight) low-level framework.  We don't use many of the features of GLFW.

**Comment by ddurnev** [comment]
Here, оn github there's no source of your version of GLFW3, only binary .a archive even without debug symbols - so I cannot debug the crash in more detail. Do you have the same nvidia X64 driver version as mine - latest beta 349.12? The backtrace showed the crash is somewhere in nvidia driver calls, but I cannot debug the driver as it is also closed-source unfortunately :( Probably there's some bug in the driver - I could help with the issue if nvidia opened up their driver sources :)
Here's my gdb session of HDRD executable when linked against supplied libglfw.a. maybe it helps:
```
(gdb) run
Starting program: /home/dad/projects/OpenGLSamples/samples/bin/linux64/HDRD 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff2306700 (LWP 2961)]
!> Failed to open joystick at /dev/input/js0
!> Failed to open joystick at /dev/input/js1
!> Failed to open joystick at /dev/input/js2
!> Failed to open joystick at /dev/input/js3
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff2306700 (LWP 2961)]
0x00007ffff47900b2 in ?? () from /usr/lib/nvidia-349/libnvidia-glcore.so.349.12
(gdb) backtrace 
#0  0x00007ffff47900b2 in ?? () from /usr/lib/nvidia-349/libnvidia-glcore.so.349.12
#1  0x00007ffff47904af in ?? () from /usr/lib/nvidia-349/libnvidia-glcore.so.349.12
#2  0x00007ffff7b0c4e7 in ?? () from /usr/lib/nvidia-349/libGL.so.1
#3  0x00007ffff7adf63a in ?? () from /usr/lib/nvidia-349/libGL.so.1
#4  0x00007ffff450eb3e in ?? () from /usr/lib/nvidia-349/libnvidia-glcore.so.349.12
#5  0x00007ffff7b33d7c in ?? () from /usr/lib/nvidia-349/libGL.so.1
#6  0x00007ffff78646aa in start_thread (arg=0x7ffff2306700) at pthread_create.c:333
#7  0x00007ffff6007eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by larsbishop** [comment]
Thanks for the details - I will look into getting the source to our version of GLFW3 posted on this site along with the other support libraries we keep as source.  I will also look into the exact driver version as I am able.  It sounds like you have a WAR for your own situation, and I've not seen others post this to our GameWorks support email as of yet.

**Comment by ddurnev** [comment]
And what is GameWorks support email(seems it's not mentioned in gameworks docs or somewhere)? I think my situation is very specific because it's linux(others use windows usually?) and nvidia beta driver.

**Comment by elect86** [comment]
Hi, I wanted to suggest to add 

glNamedBufferDataEXT(m_perMeshUniforms, sizeof(PerMeshUniforms), &m_perMeshUniforms, GL_STREAM_DRAW);

In the BindlessApp::initRendering, just after 

glGenBuffers(1, &m_perMeshUniforms);

Because if you try to start with m_usePerMeshUniforms set to false it will launch GL errors..

Sorry for writing this here but I didnt know why I couldnt commit

**Pull request closed without merging**
